project_name: opm

builds:
  - main: ./main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
    binary: opm

archives:
  - formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Akrobate
    name: openscad-package-manager
