site_name: OpenSCAD Package Manager
repo_url: https://github.com/Akrobate/openscad-package-manager
logo: assets/logo-openscad-package-manager-opm.png
site_favicon: assets/logo.ico


theme:
  name: readthedocs
  language: fr
  custom_dir: docs/overrides
  repo_url: https://github.com/Akrobate/openscad-package-manager


nav:
  - About opm: index.md
  - Quick Start: quick-start.md
  - Download and install: download-and-install-opm.md
  - Packages: openscad-packages.md
  - Usage: usage.md

